### ISSUE TITLE
factbeat not sending anything.

### ISSUE THREAD

**Issue by vdmkenny** [jarpy/factbeat#3]
This may be due to running it on a very old server, so please bear with me. I'm running a SLES 11.3 which I can unfortunately not update, with facter 2.4, and I would like to ship facter data to logstash.

My yaml file:
input:
  period: 300
  facter: "/usr/bin/facter"
output:
  logstash:
      hosts: ["http://hostname:5044"]

Running factbeat provides no output, when I quit it, this is the output:
(No data is ever shipped to logstash.)

> `/opt/factbeat # ./factbeat 
> ^Cpanic: close of nil channel
> 
> goroutine 1 [running]:
> github.com/jarpy/factbeat/beat.(_Factbeat).Stop(0xc820010800)
>   /go/src/github.com/jarpy/factbeat/beat/factbeat.go:118 +0x25
> github.com/elastic/beats/libbeat/beat.(_Beat).Stop(0xc820016240)
>   /go/src/github.com/elastic/beats/libbeat/beat/beat.go:278 +0xa2
> github.com/elastic/beats/libbeat/beat.Run(0x8f6150, 0x8, 0x8e22b8, 0x5, 0x7f68ed5c7a08, 0xc820010800, 0x0, 0x0)
>   /go/src/github.com/elastic/beats/libbeat/beat/beat.go:138 +0xd0
> main.main()
>   /go/src/github.com/jarpy/factbeat/main.go:12 +0xad
> 
> goroutine 17 [syscall, locked to thread]:
> runtime.goexit()
>   /usr/local/go/src/runtime/asm_amd64.s:1721 +0x1
> 
> goroutine 5 [syscall]:
> os/signal.loop()
>   /usr/local/go/src/os/signal/signal_unix.go:22 +0x18
> created by os/signal.init.1
>   /usr/local/go/src/os/signal/signal_unix.go:28 +0x37
> 
> goroutine 7 [sleep]:
> time.Sleep(0x3b9aca00)
>   /usr/local/go/src/runtime/time.go:59 +0xf9
> github.com/jarpy/factbeat/beat.(_Factbeat).Run(0xc820010800, 0xc820016240, 0x0, 0x0)
>   /go/src/github.com/jarpy/factbeat/beat/factbeat.go:109 +0x8e2
> github.com/elastic/beats/libbeat/beat.(_Beat).Run(0xc820016240, 0x0, 0x0)
>   /go/src/github.com/elastic/beats/libbeat/beat/beat.go:264 +0x361
> github.com/elastic/beats/libbeat/beat.(*Beat).Start(0xc820016240, 0x0, 0x0)
>   /go/src/github.com/elastic/beats/libbeat/beat/beat.go:174 +0x126
> github.com/elastic/beats/libbeat/beat.Run.func1(0xc820016240)
>   /go/src/github.com/elastic/beats/libbeat/beat/beat.go:121 +0x3c
> created by github.com/elastic/beats/libbeat/beat.Run
>   /go/src/github.com/elastic/beats/libbeat/beat/beat.go:133 +0x8d
> 
> goroutine 8 [sleep]:
> time.Sleep(0x3b9aca00)
>   /usr/local/go/src/runtime/time.go:59 +0xf9
> github.com/elastic/beats/libbeat/outputs/mode.(_SingleConnectionMode).publish(0xc820010980, 0x0, 0x0, 0xc82009b300, 0xc82005dae0, 0x0, 0x0)
>   /go/src/github.com/elastic/beats/libbeat/outputs/mode/single.go:160 +0x42b
> github.com/elastic/beats/libbeat/outputs/mode.(_SingleConnectionMode).PublishEvents(0xc820010980, 0x0, 0x0, 0xc820048b00, 0xc8202a4000, 0x1, 0x800, 0x0, 0x0)
>   /go/src/github.com/elastic/beats/libbeat/outputs/mode/single.go:84 +0x75
> github.com/elastic/beats/libbeat/outputs/logstash.(_logstash).BulkPublish(0xc82000f3a0, 0x0, 0x0, 0x0, 0xc8202a4000, 0x1, 0x800, 0x0, 0x0)
>   /go/src/github.com/elastic/beats/libbeat/outputs/logstash/logstash.go:185 +0x39d
> github.com/elastic/beats/libbeat/publisher.(_outputWorker).sendBulk(0xc8200816c0, 0xc82005dd88, 0xc8202a4000, 0x1, 0x800)
>   /go/src/github.com/elastic/beats/libbeat/publisher/output.go:89 +0x190
> github.com/elastic/beats/libbeat/publisher.(_outputWorker).onBulk(0xc8200816c0, 0xc82005dd88, 0xc8202a4000, 0x1, 0x800)
>   /go/src/github.com/elastic/beats/libbeat/publisher/output.go:66 +0x3ac
> github.com/elastic/beats/libbeat/publisher.(_outputWorker).onMessage(0xc8200816c0, 0xffffffffffff0000, 0x0, 0x0, 0x0, 0xc8202a4000, 0x1, 0x800)
>   /go/src/github.com/elastic/beats/libbeat/publisher/output.go:49 +0x79
> github.com/elastic/beats/libbeat/publisher.(_messageWorker).run(0xc8200816c0)
>   /go/src/github.com/elastic/beats/libbeat/publisher/worker.go:69 +0x424
> created by github.com/elastic/beats/libbeat/publisher.(_messageWorker).init
>   /go/src/github.com/elastic/beats/libbeat/publisher/worker.go:55 +0x11e
> 
> goroutine 10 [select]:
> github.com/elastic/beats/libbeat/publisher.(*bulkWorker).run(0xc8200692d0)
>   /go/src/github.com/elastic/beats/libbeat/publisher/bulk.go:57 +0x3ca
> created by github.com/elastic/beats/libbeat/publisher.newBulkWorker
>   /go/src/github.com/elastic/beats/libbeat/publisher/bulk.go:41 +0x20a
> 
> goroutine 11 [select, locked to thread]:
> runtime.gopark(0x9b5040, 0xc820034728, 0x8e9eb8, 0x6, 0x42db18, 0x2)
>   /usr/local/go/src/runtime/proc.go:185 +0x163
> runtime.selectgoImpl(0xc820034728, 0x0, 0x18)
>   /usr/local/go/src/runtime/select.go:392 +0xa64
> runtime.selectgo(0xc820034728)
>   /usr/local/go/src/runtime/select.go:212 +0x12
> runtime.ensureSigM.func1()
>   /usr/local/go/src/runtime/signal1_unix.go:227 +0x353
> runtime.goexit()
>   /usr/local/go/src/runtime/asm_amd64.s:1721 +0x1
> `

This may be a very dumb question, but is go required to be installed to run the binary? I assume not since filebeat works fine for me. However, my server's version of glibc is too old to install Go.

**Comment by jarpy** [comment]
Hi. Sorry for the slow reply, I've been away from the Internet.

You absolutely don't need Go installed. One of the big selling points of Go is that it creates binaries with very few dependencies.

I must admit that I haven't tested the Logstash output, so that might be a problem. The Logstash support is provided by libbeat, however. It's not something that I had to write myself.

Can you see packets going out towards Logstash? Maybe with:

```
tcpdump tcp port 5044
```

You can also try running Factbeat in debug mode with something like:

```
./factbeat -e -v -d '*'
```

Which should give some output on the terminal to look through.

Please let me know how you go.
